### ISSUE TITLE
Constant scope (Ruby 1.9?)

### ISSUE THREAD

**Issue by jphastings** [emonti/ffi-packets#1]
I'm getting a lot of complaints about non existent constants (first one is in [eth.rb at line 9](https://github.com/emonti/ffi-packets/blob/master/lib/ffi/packets/eth.rb#L11)) — without any prior knowledge of FFI it looks as though ffi_dry's helper functions don't pass the class scope along anymore.

I've been trying to fix, but it looks as though your knowledge of the system will be needed to fix all the bits that have been broken!

**Comment by emonti** [comment]
yea changes in 1.9.x class scoping require dls_layouts with ffi_dry to use absolute namespaces. it's lame... but this is all I've had the time to figure out so far.

As it happens i fixed this a while ago in the auto-parsing branch for ffi/packets
i've merged those changes up into master. hopefully this will address the issues you're having. 

Please let me know if the issue persists, or if it's ok to close out this issue for you.

Cheers

**Comment by emonti** [comment]
tests appear to be passing now so i'm closing this out. please open another ticket if issues persist.

**Comment by jphastings** [comment]
Sorry I haven't gotten back to you sooner — the woes of having a 9-to-5 — thanks very much!
