### ISSUE TITLE
Umm… How to use it?

### ISSUE THREAD

**Issue by jphastings** [emonti/ffi-packets#2]
I know I'm being an idiot here, but without an example I have no idea how to use this library!

Could you add a minimal example to the readme for people like me who are very unfamiliar with FFI?

I'm currently using:

```
require 'ffi-pcap'
require 'ffi/packets'

pcap = FFI::PCap::Live.new(:dev => 'lo0',
                           :timeout => 1,
                           :promisc => true,
                           :handler => FFI::Packets)

pcap.loop() do |this,pkt|
  p pkt.methods
  putc "\n"
end
```

But I'm not sure how I could get the source ip for the packet!

**Comment by tjarratt** [comment]
FFI::PCap suggests using this library, but this library has a relatively high barrier to entry.

When I figure out how to use this library with ffi-pcap, I'll fork and suggest improvements for the README.

**Comment by DanyHenriquez** [comment]
I know this is a couple of years ago, but any info?

**Comment by nemski** [comment]
Say you have a FFI::Pcap::Packet object called packet:

`irb(main):025:0> packet
=> #<FFI::PCap::Packet:0x00000001b8ded0 @header=#<FFI::PCap::PacketHeader:0x00000001b8e088 @dsl_metadata=[{:desc=>"time stamp", :name=>:ts, :type=>FFI::PCap::TimeVal}, {:desc=>"length of portion present", :name=>:caplen, :type=>:bpf_uint32}, {:desc=>"length of packet (off wire)", :name=>:len, :type=>:bpf_uint32}]>, @body_ptr=#<FFI::MemoryPointer address=0x00000001f4a0e0 size=66>>`

you can instantiate a FFI::Packets object like so:

`p = FFI::Packets::Ip::Hdr.new(packet.body_ptr)`

but this, at least for me, returns the incorrect source/destination IP:

`irb(main):009:0> p.src
=> "8.0.69.0"
irb(main):010:0> p.dst
=> "0.52.241.18"`

**Comment by patrobinson** [comment]
You need to provide a FFI::MemoryPointer of just the Ip header or TCP/UDP header. I wrote a library to do this https://github.com/nemski/r_tcp_ip
